# SauceDemo URLs and Configuration
base.url=https://www.saucedemo.com
ui.timeout=10

# REST API Configuration
api.base.url=https://reqres.in
api.timeout=5
api.key=reqres_58de021486384306a911aad55b795d2b

# Browser Configuration
browser.name=chrome
headless.mode=false

# Logging
log.level=INFO 

#credentials
username=standard_user
password=secret_sauce
